/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuditApply: typeof import('./src/components/order/refund/AuditApply.vue')['default']
    Header: typeof import('./src/components/order/Header.vue')['default']
    OrderList: typeof import('./src/components/order/OrderList.vue')['default']
    RefundList: typeof import('./src/components/order/refund/RefundList.vue')['default']
    Result: typeof import('./src/components/order/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
